### ISSUE TITLE
slackfix crashes on openSUSE Leap 15.4

### ISSUE THREAD

**Issue by juliogonzalez** [frispete/slackfix#1]
First: thanks a lot for slackfix!

I know the `README.md` mentions Tumbleweed, but seems Leap 15.4 is affected by the same problem (and I suspect 15.5).

Since https://build.opensuse.org/package/show/home:frispete:Tumbleweed/slackfix has a 15.4 repo, I thought it could be interesting to report that it crashes there:

```
Traceback (most recent call last):
  File "/usr/bin/slackfix", line 11, in <module>
    load_entry_point('slackfix==0.1.2', 'console_scripts', 'slackfix')()
  File "/usr/lib/python3.6/site-packages/slackfix.py", line 215, in main
    return run()
  File "/usr/lib/python3.6/site-packages/slackfix.py", line 161, in run
    text = True) as p:
TypeError: __init__() got an unexpected keyword argument 'text'
```
That's because python 3.6 (default on Leap 15.4 and Leap 15.5) does not does not have the keyword `text` for `subprocess.Popen`

However, Leap 15.4 has python 3.9 available, and Leap 15.5 has python 3.11 available, so I prepared https://build.opensuse.org/request/show/1075079 to use them.

I think it's a better approach than adapting the code to the already unsupported python 3.6, but let me know if you think otherwise :-)

**Comment by juliogonzalez** [comment]
My SR got rejected, as @frispete decided to fix the code: https://build.opensuse.org/request/show/1075079#status-history-16861434

I confirm 0.1.3 (https://build.opensuse.org/package/rdiff/home:frispete:Tumbleweed/slackfix?linkrev=base&rev=5), fixed the issue and openSUSE Leap 15.4 works now.

Closing this issue.

Thanks a lot for the fix!
